### ISSUE TITLE
Navbar is not only see-through but also not clickable when user scrolls down!

### ISSUE THREAD

**Issue by Evie-Skinner18** [Evie-Skinner18/sparta-global-portfolio#32]
Time to finally fix that 'feature'.

The navbar of my website looks like a solid yellow when the user statically views the page, but when they scroll down, it reveals itself to be transluscent. At first I thought that was quite cool so I left the bug! However, I've just realised that the navbar's links are not clickable when it's transluscent. Have decided to finally try to fix/ask for help!

Happy Hacktoberfest!  :skull:

**Comment by RajkumarMittal** [comment]
can i contribute? to improve the nabars @Evie-Skinner18

**Comment by swas1820** [comment]
Hey!
I would like to solve the problem and contribute to this.

**Comment by FalsePozitive** [comment]
EDIT: I see I was beaten to this by the current pull request. 
Hi the fix  is to  add z-index:1 as per below to line 22 of style.css: : 
.navalicious {
  font-family: 'Rubik', sans-serif;
  text-transform: uppercase;
  background-color: gold;
  min-height: 40px;
  padding: 10px;
  position: fixed;
  width: 100%;
  font-weight: 600;
  z-index:1
}

**Comment by tadhglewis** [comment]
I have already created a pull request: https://github.com/Evie-Skinner18/sparta-global-portfolio/pull/33

z-index 9999; insures that it likely will never happen again but z-index: 1; means if @Evie-Skinner18 ever uses z-index 1 or 2 on another element the same problem will occur.

As the navbar will always be the highest element this is a better solution

**Comment by FalsePozitive** [comment]
> I have already created a pull request: #33
> 
> z-index 9999; insures that it likely will never happen again but z-index: 1; means if @Evie-Skinner18 ever uses z-index 1 or 2 on another element the same problem will occur.
> 
> As the navbar will always be the highest element this is a better solution

Ya, I've noted this in my edit above.

**Comment by Evie-Skinner18** [comment]
Really appreciate all your responses, thank you ever so much for your help everyone! :heart_eyes: :monkey_face: :tada:
